In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Sample scalar and array inputs
scalar = 3.7 #changing the scalar value
arr = np.array([1.5, 2.5, 3.5, 4.5, 5.5,6.5]) # took a new 6 elements

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [ 0.99749499  0.59847214 -0.35078323 -0.97753012 -0.70554033  0.21511999]
cos: [ 0.0707372  -0.80114362 -0.93645669 -0.2107958   0.70866977  0.97658763]
tan: [14.10141995 -0.7470223   0.37458564  4.63733205 -0.99558405  0.2202772 ]
asin: [0.23286818 0.39479112 0.5686103  0.76468218 1.00872652 1.57079633]
acos: [1.33792815 1.17600521 1.00218603 0.80611415 0.5620698  0.        ]
atan: [0.98279372 1.19028995 1.29249667 1.35212738 1.39094283 1.418147  ]
exp: [  4.48168907  12.18249396  33.11545196  90.0171313  244.69193226
 665.14163304]
log: [0.40546511 0.91629073 1.25276297 1.5040774  1.70474809 1.87180218]
abs: [1.5 2.5 3.5 4.5 5.5 6.5]
sqrt: [1.22474487 1.58113883 1.87082869 2.12132034 2.34520788 2.54950976]
rem: [1.5 0.5 1.5 0.5 1.5 0.5]
round: [2. 2. 4. 4. 6. 6.]
floor: [1. 2. 3. 4. 5. 6.]
ceil: [2. 3. 4. 5. 6. 7.]


In [3]:
# Creating a 3x2 matrix
matrix = np.array([[1.5, 2.5], [3.5, 4.5], [5.5,6.5]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[1.5 2.5]
 [3.5 4.5]
 [5.5 6.5]]

sin:
 [[ 0.99749499  0.59847214]
 [-0.35078323 -0.97753012]
 [-0.70554033  0.21511999]]

cos:
 [[ 0.0707372  -0.80114362]
 [-0.93645669 -0.2107958 ]
 [ 0.70866977  0.97658763]]

tan:
 [[14.10141995 -0.7470223 ]
 [ 0.37458564  4.63733205]
 [-0.99558405  0.2202772 ]]

asine:
 [[0.23286818 0.39479112]
 [0.5686103  0.76468218]
 [1.00872652 1.57079633]]

acosine:
 [[1.33792815 1.17600521]
 [1.00218603 0.80611415]
 [0.5620698  0.        ]]

atangent:
 [[0.98279372 1.19028995]
 [1.29249667 1.35212738]
 [1.39094283 1.418147  ]]

exp:
 [[  4.48168907  12.18249396]
 [ 33.11545196  90.0171313 ]
 [244.69193226 665.14163304]]

log (natural):
 [[0.40546511 0.91629073]
 [1.25276297 1.5040774 ]
 [1.70474809 1.87180218]]

abs:
 [[1.5 2.5]
 [3.5 4.5]
 [5.5 6.5]]

sqrt:
 [[1.22474487 1.58113883]
 [1.87082869 2.12132034]
 [2.34520788 2.54950976]]

rem (remainder when divided by 2):
 [[1.5 0.5]
 [1.5 0.5]
 [1.5 0.5]]

round:
 [[2. 2.]
 [4. 4.]
 [6. 6.]]

floor:
 

In [4]:
# Creating a 2x3 matrix
matrix = np.array([[1.2, 2.2, 3.2], [4.5, 5.5, 6.5]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[1.2 2.2 3.2]
 [4.5 5.5 6.5]]

sin:
 [[ 0.93203909  0.8084964  -0.05837414]
 [-0.97753012 -0.70554033  0.21511999]]

cos:
 [[ 0.36235775 -0.58850112 -0.99829478]
 [-0.2107958   0.70866977  0.97658763]]

tan:
 [[ 2.57215162 -1.37382306  0.05847385]
 [ 4.63733205 -0.99558405  0.2202772 ]]

asine:
 [[0.18568051 0.34528146 0.51473901]
 [0.76468218 1.00872652 1.57079633]]

acosine:
 [[1.38511582 1.22551487 1.05605732]
 [0.80611415 0.5620698  0.        ]]

atangent:
 [[0.87605805 1.14416883 1.26791146]
 [1.35212738 1.39094283 1.418147  ]]

exp:
 [[  3.32011692   9.0250135   24.5325302 ]
 [ 90.0171313  244.69193226 665.14163304]]

log (natural):
 [[0.18232156 0.78845736 1.16315081]
 [1.5040774  1.70474809 1.87180218]]

abs:
 [[1.2 2.2 3.2]
 [4.5 5.5 6.5]]

sqrt:
 [[1.09544512 1.4832397  1.78885438]
 [2.12132034 2.34520788 2.54950976]]

rem (remainder when divided by 2):
 [[1.2 0.2 1.2]
 [0.5 1.5 0.5]]

round:
 [[1. 2. 3.]
 [4. 6. 6.]]

floor:
 [[1. 2. 3.]
 [4. 5. 6.]]

ceil:
 [[2. 3

In [5]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

vector_matrix = np.array([[2.1, 4.7, 3.3],
                          [1.9, 5.6, 0.8]])

print("\n2x3 Vector Matrix:\n", vector_matrix)

# Max & Min with indices
print("Max value:", np.max(vector_matrix))
print("Min value:", np.min(vector_matrix))
print("Index of Max:", np.unravel_index(np.argmax(vector_matrix), vector_matrix.shape))
print("Index of Min:", np.unravel_index(np.argmin(vector_matrix), vector_matrix.shape))

# Vector length (L2 Norm)
print("Vector length:", np.linalg.norm(vector_matrix))

# Sorting
print("Row-wise sorted descending:\n", np.sort(vector_matrix)[:, ::-1])
print("Entire matrix sorted descending:\n", np.sort(vector_matrix.flatten())[::-1])

# Sum, Product
print("Sum:", np.sum(vector_matrix))
print("Product:", np.prod(vector_matrix))

# Median, Mean, Standard Deviation
print("Median:", np.median(vector_matrix))
print("Mean:", np.mean(vector_matrix))
print("Standard Deviation:", np.std(vector_matrix))


2x3 Vector Matrix:
 [[2.1 4.7 3.3]
 [1.9 5.6 0.8]]
Max value: 5.6
Min value: 0.8
Index of Max: (np.int64(1), np.int64(1))
Index of Min: (np.int64(1), np.int64(2))
Vector length: 8.54400374531753
Row-wise sorted descending:
 [[4.7 3.3 2.1]
 [5.6 1.9 0.8]]
Entire matrix sorted descending:
 [5.6 4.7 3.3 2.1 1.9 0.8]
Sum: 18.400000000000002
Product: 277.24435200000005
Median: 2.7
Mean: 3.066666666666667
Standard Deviation: 1.6619934483090546
